### ISSUE TITLE
Can I use the packages instead of xrdp-egfx and xorgxrdp-egfx?

### ISSUE THREAD

**Issue by harrier77** [DesktopECHO/xrdp-xorgxrdp-binaries#1]
I am using kde neon on wls2  with xrdp. To get acceleration it is necessary to use the xrdp server with your 2 packages xrdp-egfx and xorgxrdp-egfx from  [kWSL](https://github.com/DesktopECHO/kWSL).
Are the packages in this repository [xrdp-xorgxrdp-binaries](https://github.com/DesktopECHO/xrdp-xorgxrdp-binaries) a new version of the similar packages in kWSL? And when will they be available on official ubuntu repositories?

**Comment by DesktopECHO** [comment]
These are test packages built from xrdp-devel, which is version 0.10.0 with x264 support.  
You're welcome to try them out but no guarantees on functionality.  If they do work for you let me know.
